deploy_demo:
  stage: deploy
  image: tetraweb/php:7.1
  
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client sshpass rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - rsync -hrvz -e ssh  --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='__MACOSX/design' --exclude='upload' --exclude='uploaded_images' --exclude='.phpintel' --update ./ root@206.189.137.174:/var/www/html/

  only:
    - master    
